### ISSUE TITLE
Seg Fault on World

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#1]
I tried running mcpe_viz on a file that I received from a contact on reddit.  He had taken the old classic "nyan" seed and made it work as an infinite world on 0.12.x.

I tried it in my version of MCPE on my phone and it seems to work perfectly well, however, when I run mcpe_viz on it I get a seg fault.

Here is the output:
`mcpe_viz --grid --db ~/documents/shared/nyan/ --out ~/documents/shared/mcpe/nyan
mcpe_viz v0.0.4 by Plethora777
Reading XML from /home/paul/.mcpe_viz/mcpe_viz.xml
Reading config from /home/paul/.mcpe_viz/mcpe_viz.cfg
  Adding 'hide-top' block: dimId=1 blockId=  7 (0x07) (hide-top: nether - Bedrock)
  Adding 'hide-top' block: dimId=1 blockId= 87 (0x57) (hide-top: nether - Netherrack)
  Adding 'hide-top' block: dimId=1 blockId= 10 (0x0a) (hide-top: nether - Lava S)
  Adding 'hide-top' block: dimId=1 blockId= 11 (0x0b) (hide-top: nether - Stationary Lava S)
  Adding 'hide-top' block: dimId=0 blockId= 16 (0x10) (hide-top: overworld - Coal Ore)
  Adding 'hide-top' block: dimId=0 blockId= 15 (0x0f) (hide-top: overworld - Iron Ore)
  INFO: Adding 'force-top' block: dimId=0 blockId= 56 (0x38) (force-top: overworld - Diamond Ore)
  INFO: Adding 'force-top' block: dimId=0 blockId=120 (0x78) (force-top: overworld - End Portal Frame)
  INFO: Adding 'force-top' block: dimId=0 blockId= 54 (0x36) (force-top: overworld - Chest E)
parseLevelFile: name=/home/paul/documents/shared/nyan//level.dat version=4 len=446
Found World Spawn: x=128 y=64 z=128
Level name is [nyan]
DB Open: dir=/home/paul/documents/shared/nyan/
DB Open Status: OK
Scan keys to get world boundaries
  2299 records
Parse all leveldb records
Player Position=(129.543091, 76.620003, 110.118469) at image (129, 110) -- Rotation=(3926.182373, 11.269871)
Read 2299 records
Status: OK
Do Output: overworld
  Generate Image
    Info: World (0, 0) is at image (0, 0)
Segmentation fault (core dumped)`

The file for the world itself is available at: https://www.dropbox.com/s/sgmf2mxvxovriic/nyan.zip?dl=0

The log file for the attempted conversion is available at: https://www.dropbox.com/s/n9agp9spk1jleq4/nyan.log?dl=0

**Comment by Plethora777** [comment]
Thanks for the bug report.  The leveldb for the world had one really weird record (bad coordinates).  I added code to avoid this issue.  Fixed in today's push.
