### ISSUE TITLE
DLLs detected as Trojan Threath

### ISSUE THREAD

**Issue by juan-franco** [Plethora777/mcpe_viz#10]
Hi, I have tested mcpe_viz yesterday and after the first run Windows 10 defender said that some .dll files included in win64 version are infected with a trojan horse malware. Can you review this? I will provide you more details this evening.

**Comment by Plethora777** [comment]
That's very strange as the included DLLs come directly from the MinGW packages on a Fedora 24 machine.  (That is: the DLLs are part of a package that a lot of developers use on a regular basis)

Where did you download mcpe_viz from?

More details would be very welcome!

**Comment by juan-franco** [comment]
Hi, I have downloaded from the link at "Quick Start -- How to run it on Windows with a GUI" section of the readme.md. 

The files are: 
D:\Documents\Minecraft\mcpe_viz-master\mcpe_viz.win64\QtNetwork4.dll
D:\Documents\Minecraft\mcpe_viz-master\mcpe_viz.win64\libstdc++-6.dll

The alert info refers to: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fPeals.A!cl&threatid=2147690472&enterprise=0

I have just tried w32 version and no alert was detected

I hope that this helps, the application is really useful, great work!

Regards, Juan

**Comment by Plethora777** [comment]
In that microsoft link, towards the bottom it says:

> NOTE: On December 6, 2016, an incorrect detection for our cloud-based protection for Trojan:Win32/Peals.A!cl was identified and immediately fixed. To ensure that this issue is remediated, you can do a forced daily update to download your Microsoft antimalware and antispyware software. For details, see Updating your Microsoft antimalware and antispyware software.

Could you follow those instructions and check again?

**Comment by juan-franco** [comment]
I have updated the software right now, unzipped both versions, executed a quick scan and it didn't found any threat, all clean!

Thanks!!
