### ISSUE TITLE
 Update for 1.0 not displaying "force-top" blocks

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#12]
I've just run the latest update - thanks for that - using the following command:

mcpe_viz --db /opt/shared/4lkBAJz-AAA\=/ --out /opt/shared/mcpe/Ísland --html-most --no-force-geojson

and the blocks I've put in my mcpe_viz.cfg to be forced to top are not displaying at the top.

My .cfg looks like this: (Edit: I've no idea why this text is displaying so huge!)

# config file for mcpe_viz

# hide blocks from overview map
# hide-top: dimensionId blockId
# (dimensionId=0 is overworld; dimensionId=1 is nether)
# (blockId is from mcpe_viz.xml)

# force blocks to appear on the overview map even if they are covered
# force-top: dimensionId blockId
# (dimensionId=0 is overworld; dimensionId=1 is nether)
# (blockId is from mcpe_viz.xml)

# add blocks to the geojson file so that they will be available in the web app
# **PLEASE NOTE** adding common blocks will make your geojson file HUGE and possibly cause problems with the web app
# geojson-block: dimensionId blockId
# (dimensionId=0 is overworld; dimensionId=1 is nether)
# (blockId is from mcpe_viz.xml)

# add mappings for remote player id's
# player-id: playerId playerName
# (playerId is the numerical string used in the leveldb files)
# (playerName is the name you would like displayed in the web app)

# in the nether, hide bedrock, netherrack and lava so that we can see more interesting details
hide-top: 1 0x07
hide-top: 1 0x57
hide-top: 1 0x0a
hide-top: 1 0x0b

# example of force-top - force spawners to top
force-top: 0 0x34
force-top: 1 0x34
force-top: 0 0x38 
force-top: 0 0x42
force-top: 0 0x78

# add "special" blocks to the geojson file for use in the web app
# For example, "End Portal Frame" block
geojson-block: 0 0x78

# example of player-id
# player-id: 123456789 SomeUserName

In particular, I'm expecting to see diamonds and railtrack at the surface, but I do not.

**Comment by Plethora777** [comment]
Yep.  Thanks for pointing that out.  Cubic chunks are really cool, but they require a lot of new code to support the stuff we did before when the entire chunk's data was in each record.  I'll add it to the todo list.  I expect I can resolve it quickly.

FWIW --geojson-block still works right now :)

**Comment by Plethora777** [comment]
Just pushed an update that should fix it.  Let me know.

**Comment by phunni** [comment]
yup - that seems to have fixed it - thanks!

**Comment by Plethora777** [comment]
Nice.  Thanks!
