### ISSUE TITLE
MCPEVIZ Crash After Entering the End

### ISSUE THREAD

**Issue by Shkyrockett** [Plethora777/mcpe_viz#13]
Nice work getting MCPE VIZ working with the 1.0 update. 
I did find though, that I encountered a crash when I ran MCPEVIZ on a world where I had entered the End. 
Here is a world to repro the crash: [MCPEVIZ Crash Repro.mcworld.zip](https://github.com/Plethora777/mcpe_viz/files/671517/MCPEVIZ.Crash.Repro.mcworld.zip)

**Comment by rodrigojxd** [comment]
I also noticed that.

**Comment by Plethora777** [comment]
Just pushed an update that should fix this.  Give it a try.

@Shkyrockett THANK YOU for the world file - saved me a bunch of time.

**Comment by Shkyrockett** [comment]
Working great. Thanks!
