### ISSUE TITLE
Biome View Mixed with Ocean

### ISSUE THREAD

**Issue by ryanscampbell** [Plethora777/mcpe_viz#14]
The Biome view seems to have some issues with showing new area explored since the MCPE 1.0 update.
The top 4 pixel rows shows the right biome, but the bottom 12 show a light blue which it incorrectly shows as an ocean biome.

This screenshot shows the Biomes explored in 0.16.2 on the left and the new areas explored since 1.0 on the right:
![image](https://cloud.githubusercontent.com/assets/24706498/21463865/081b33ca-c92d-11e6-8560-efc2631a4d51.png)

**Comment by Plethora777** [comment]
Thanks for pointing that out.  Turns out that in MCPE v1.0 the per chunk column data is a bit different.  I just pushed an update that should resolve this.  Give it a try.

**Comment by ryanscampbell** [comment]
The biome issue seems to be resolved, thanks for the fix.
