### ISSUE TITLE
Spawnable Blocks Appear at Odd Places at Previous World Height Limit

### ISSUE THREAD

**Issue by kylesutton** [Plethora777/mcpe_viz#17]
Hey Plethora,

In checking out the fixes for #15, I found that spawnable blocks were showing on top of a structure that was at the prior-to-v1.0 height limit.

Here is the structure at one layer underneath the _lit_ layer:
![image](https://cloud.githubusercontent.com/assets/11877271/21513332/275f90f4-cc85-11e6-8b70-97f030d9ed0c.png)

Here is the structure at the _lit_ layer, with several rings of jack-o-lanterns & torches:
![image](https://cloud.githubusercontent.com/assets/11877271/21513350/547dfa76-cc85-11e6-8d35-2c37f8fee3a4.png)

Here is the structure at one layer above the _lit_ layer:
![image](https://cloud.githubusercontent.com/assets/11877271/21513418/5184e11c-cc86-11e6-89dc-af8eb14ebbda.png)

It seems to suggest that the blocks one above jack-o-lanterns are spawnable and that a ring one block up and one over from a ring of torches is spawnable.

I'm also getting several of these messages in the map generation log:

`WARNING: UNKNOWN CHUNK VERSION!  overworld 0x76 chunk (world format version): v=3`

Is this suggesting that it's using the v2 processing functions because it doesn't recognize the `v=3` world format version token, and if so, is there an option to force it to use the v3 functions/world height?

Thanks,
Kyle

**Comment by Plethora777** [comment]
Interesting.  It could be that the those blocks near the old build limit have not had their block light values updated properly by MCPE.  Could you go walk around these areas and then re-run mcpe_viz and see if things are different?

Re the UNKNOWN CHUNK VERSION -- that's innocuous.  I need to update the code to not print that since we do actually know about v=3 (that's the version reported by MCPE v1.0 cubic chunks)

**Comment by kylesutton** [comment]
It took some work, but it seems to have fixed itself.  For posterity:

1. Went underneath layer 128 in tall structure and walked around, regenerated map, blocks still show as spawnable
2. Went on top of layer 128 and walked around, regenerated map, same result
3. Went up 5 or so blocks above 128, regenerated map, same result
4. Put torches about 5 blocks above and 2 blocks above 128, regenerated map, spawnable blocks gone! _(though not all errant spawnable blocks were covered by newly placed torches)_
5. Removed new torches so that structure is as it was, regenerated map, spawnable blocks still gone!

Thanks,
Kyle
