### ISSUE TITLE
Crash During Gen of Christmas Pack World

### ISSUE THREAD

**Issue by kylesutton** [Plethora777/mcpe_viz#19]
Hey Plethora,

Got this when running a map gen on a world created with the _Festive Mash-Up 2106_ pack:
```
C:\Programs\Minecraft\MCPEViz>mcpe_viz --flush --auto-tile --db tIQGAEuvsAE= --out Out/Christmas --html-all
mcpe_viz v0.0.29 by Plethora777
Reading XML from ./mcpe_viz.xml
Reading config from ./mcpe_viz.cfg
parseLevelFile: name=tIQGAEuvsAE=/level.dat version=4 len=835
  Found World Spawn: x=33 y=64 z=-144
  Level name is [Festive Mash-up 2016]
DB Open: dir=tIQGAEuvsAE=
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(-46 56) Z=(-57 47)
  Bounds (pixel): DimId=0 X=(-736 896) Z=(-912 752) Image=(1648 1680)
  Bounds (chunk): DimId=1 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=1 X=(0 0) Z=(0 0) Image=(16 16)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  43872 records
Active 'hide-top', 'force-top', and 'geojson-block':
  'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
  'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
  'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
  'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
  'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
Parse all leveldb records
WARNING: getItemName failed to find variant id=383 extradata=14
WARNING: getItemName failed to find id=383 extradata=14
WARNING: getItemName failed to find variant id=383 extradata=14
WARNING: getItemName failed to find id=383 extradata=14
  Processing records: 10000 / 43872 (22.8%)
  Processing records: 20000 / 43872 (45.6%)
Player Position: Dimension=0 Pos=(4.46755, 67.3688, -342.747 @ image 740, 569) Rotation=(-195.631653, 2.627911)
WARNING: getItemName failed to find variant id=383 extradata=14
WARNING: getItemName failed to find id=383 extradata=14
WARNING: getItemName failed to find variant id=383 extradata=14
WARNING: getItemName failed to find id=383 extradata=14
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Is this an issue, in general, with odd blocks/formations in add-on packs?

Thanks,
Kyle

**Comment by Plethora777** [comment]
Interesting.  I've not seen that sort of crash before.  I'd like to track it down.  Can you zip and post that world somewhere so I can grab it?

**Comment by TheDiamondYT1** [comment]
@Plethora777 You should add a way to automatically zip and upload the world online with the username of the user who experienced the crash and also add the username in the crash report so you can match the two

**Comment by kylesutton** [comment]
Let me know if this works:

[kylesutton.festive-mash-up-2016.zip](https://github.com/Plethora777/mcpe_viz/files/678298/kylesutton.festive-mash-up-2016.zip)

Thanks,
Kyle

**Comment by Plethora777** [comment]
Got it - thanks!  Weird error.  I need to poke at it a bit more.  Is this ZIP the fresh pack or after you have played a bit?

**Comment by kylesutton** [comment]
I believe this one had a bit of exploration, but probably only as far out as the minecart circuit.

**Comment by Plethora777** [comment]
Ok thanks!

**Comment by Plethora777** [comment]
I found the source of the error but it's quite strange.  Could you try this -- open that world, move around a bit and then re-run mcpe_viz on it to see if the error persists.

Background -- I see how to address the error, but it's weird enough that I'm wondering if it is a transient glitch, possibly having to do with some of the beta versions... 

Thanks!

**Comment by kylesutton** [comment]
Here's a new one and an updated version of the original one.  Both have the same issue.

[kylesutton.festive-mash-up-2016.tIQGAEuvsAE=.zip](https://github.com/Plethora777/mcpe_viz/files/707019/kylesutton.festive-mash-up-2016.tIQGAEuvsAE.zip)
[kylesutton.festive-mash-up-2016.ONkAAOw4AAA=.zip](https://github.com/Plethora777/mcpe_viz/files/707020/kylesutton.festive-mash-up-2016.ONkAAOw4AAA.zip)

Thanks,
Kyle

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
