### ISSUE TITLE
How do I view spawnable blocks?

### ISSUE THREAD

**Issue by ryanscampbell** [Plethora777/mcpe_viz#20]
This is more of just a question of ignorance that an issue, I just didn't know better place to ask.

I looked on the site, and in the Readme, but I didn't see anything that explained how to You spottable blocks.

**Comment by Plethora777** [comment]
Use the command-line switch --check-spawn and then see Blocks menu item in the web ui.

**Comment by ryanscampbell** [comment]
Got it, and now I see it in the readme. Thanks :-)
