### ISSUE TITLE
WARNING: Did not find block variant for block(Large Flowers) with blockdata=15 (0xf) MSG1

### ISSUE THREAD

**Issue by shellbj** [Plethora777/mcpe_viz#22]
Got this warning when parsing my world:
> WARNING: Did not find block variant for block(Large Flowers) with blockdata=15 (0xf) MSG1

Not sure if this is an actionable thing or not.  The captured log file doesn't have anything else useful in relating to the warning.

This is a 1.0 generated world.

**Comment by Plethora777** [comment]
That warning just lets us know that there is an object in the world that is not recognized by the data in our XML file.  There are a few of these that are still lingering.  If you can confirm what the item is, we can update the XML file.

**Comment by juan-franco** [comment]
Hi, I have some of them:

WARNING: Did not find block variant for block(Large Flowers) with blockdata=14 (0xe) MSG3
From http://minecraft.gamepedia.com/Flower, if I understood it right, blockdata 14 is the upper part of a "Rose Bud". 

WARNING: Did not find block variant for block(Large Flowers) with blockdata=15 (0xf) MSG3
From http://minecraft.gamepedia.com/Flower, if I understood it right, blockdata 15 is the upper part of a "Peony". 

WARNING: Did not find block variant for block(Anvil) with blockdata=6 (0x6) MSG3
From http://minecraft.gamepedia.com/Anvil, blockdata 6 is "Slightly Damaged Anvil (West/East)"

Bye!

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
