### ISSUE TITLE
Don't intermix tabs/spaces for indention

### ISSUE THREAD

**Issue by shellbj** [Plethora777/mcpe_viz#24]
Pick one please!

**Comment by kylesutton** [comment]
+1 for tabs, though there are a number of places where the current styling wouldn't fit well with their use (definition of _do_chunk_v3 function, for instance).

**Comment by shellbj** [comment]
I think spaces would be the least impactful; most indention is spaces until you get to a natural 8 character tab stop.

**Comment by Plethora777** [comment]
I use emacs, and well... I don't think this is a big deal :)

**Comment by shellbj** [comment]
Then do everyone a favor and add this to your settings `(setq-default indent-tabs-mode nil)`

**Comment by Plethora777** [comment]
Thanks very much for the tip -- I will check it out!

I didn't mean to be dismissive, I just did not know a reasonable fix for it without changing my editor, which would be a drag.  I appreciate it.

**Comment by Plethora777** [comment]
Updating to add a .dir-locals.el file with the command suggested by @shellbj 
Thanks.
