### ISSUE TITLE
Showing Polar Bears from the "Passive Mobs" menu has wrong label

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#25]
The Bears all appear (as far as I can tell), but instead of being labelled "Polar Bear" they are labelled "*UNKNOWN: id=28 0x1c"

Hope that makes sense!

**Comment by Plethora777** [comment]
It does.  Is this on the latest version of mcpe_viz?  The polar bear label should come from the XML file.

It would be faster work for me if you could zip that world file and send it along :)

**Comment by phunni** [comment]
My apologies - I hadn't copied the latest XML to ~/.mcpe_viz

Having done that it all works perfectly...

**Comment by Plethora777** [comment]
No worries - I'll close this :)
