### ISSUE TITLE
Objects position offset

### ISSUE THREAD

**Issue by juan-franco** [Plethora777/mcpe_viz#27]
Hi, since the update for MCPE v1.0 when I activate one object overlay like "chests" or "mob spawner" the markers are showed with an offset of about 330 meters to the left and 50 meters above the real location. I am using version 0.0.30 for Win64 and in previous versions it was fine.

![image](https://cloud.githubusercontent.com/assets/5711252/21826919/ae9d3ecc-d789-11e6-8bc4-80fdb08b3f53.png)

Thanks an keep on going!

**Comment by Plethora777** [comment]
Strange.  Can you zip the world file and send me a link?

**Comment by juan-franco** [comment]
I will try with a smaller world and if it has the same issue I upload it, otherwise I let you know...

**Comment by juan-franco** [comment]
Sorry!!, it's my fault!! I had output mode selector in "All Images" (not sure why), I tried changing to "Web App with ALL images" and now its solved. 

Regards!!
