### ISSUE TITLE
Enderchests

### ISSUE THREAD

**Issue by cbos0503** [Plethora777/mcpe_viz#28]
Is it possible to see the contents of a player's enderchest?

**Comment by TheDiamondYT1** [comment]
No

**Comment by TheDiamondYT1** [comment]
Wait nm i thought this was a nukkt issue

**Comment by Thunder33345** [comment]
I dont think right now but may be implementable

**Comment by Plethora777** [comment]
I will look into it!

**Comment by cbos0503** [comment]
YES! Thanks Plethora!!

**Comment by Plethora777** [comment]
Just pushed an update that should resolve this.  

Note -- Because of the way ender chests work, ender chest inventories are shown in the 'Player' object, not in the Ender Chest itself :)

**Comment by cbos0503** [comment]
Nice... you rock! Thanks for the ridiculously quick response and update!!! :)
