### ISSUE TITLE
Viz Error

### ISSUE THREAD

**Issue by Harvey9877** [Plethora777/mcpe_viz#33]
Hello,

I'm getting the below error when trying to use viz.  I'm playing MCPE 1.05 on iOS 10.  The world is a Realm world that I downloaded and transferred to my Windows 10 PC.  I've tried switching between the 32 and 64 bit versions.  Any thoughts would be appreciated.  Thanks!

mcpe_viz v0.0.31 by Plethora777
Reading XML from C:\Users\k\Downloads\Viz\mcpe_viz-master/mcpe_viz.xml
Reading config from C:\Users\k\Downloads\Viz\mcpe_viz-master/mcpe_viz.cfg
parseLevelFile: name=C:/Users/k/Downloads/games/com.mojang/minecraftWorlds/WNgBADzZAQA=/level.dat version=5 len=853
  Found World Spawn: x=128 y=64 z=128
  Level name is [Realm1]
DB Open: dir=C:/Users/k/Downloads/games/com.mojang/minecraftWorlds/WNgBADzZAQA=
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(-90 134) Z=(-65 109)
  Bounds (pixel): DimId=0 X=(-1440 2144) Z=(-1040 1744) Image=(3600 2800)
  Bounds (chunk): DimId=1 X=(-11 17) Z=(-21 10)
  Bounds (pixel): DimId=1 X=(-176 272) Z=(-336 160) Image=(464 512)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  107665 records
Active 'hide-top', 'force-top', and 'geojson-block':
  'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
  'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
  'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
  'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
  'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
Parse all leveldb records

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast

**Comment by bsavage81** [comment]
I have this same issue. scanning with most images was working, but now after 1.1 update, it gives the same error.

**Comment by Plethora777** [comment]
Just pushed an update - give it a try.

**Comment by Plethora777** [comment]
I believe the recent update solved this.  Feel free to open another ticket if there are other problems. Thanks.
