### ISSUE TITLE
Parse all leveldb records

### ISSUE THREAD

**Issue by DjGamewon** [Plethora777/mcpe_viz#35]
Hello!

When I try to run MCPE Viz on my world, in the progress window, it says parse all leveldb records and doesn't do anything.
Here's what the progress window says:
[https://pastebin.com/tEbw8qNa](https://pastebin.com/tEbw8qNa)
And here's what the output says:
[https://pastebin.com/RMa6Mgfq](https://pastebin.com/RMa6Mgfq)

**Comment by DjGamewon** [comment]
Just tested it out - created a new map and it worked, the 2 I had made about 2 weeks ago didn't work, I've used Blocktopograph, but I also tested that on the new world and it didn't affect it.

**Comment by DjGamewon** [comment]
Found out the issue but not the fix - When I load more chunks than the ones I've spawned in it creates that error. :(

**Comment by Plethora777** [comment]
Can you zip and send along a dropbox (or other) link for the world files that do not work?

**Comment by Plethora777** [comment]
Just pushed an update - give it a try.

**Comment by Plethora777** [comment]
I believe this is solved by the recent update.  Feel free to open another ticket if there are other issues.  Thanks.
