### ISSUE TITLE
Crash on 1.1.0 map

### ISSUE THREAD

**Issue by rawdr** [Plethora777/mcpe_viz#36]
Starting failing to compile - I am assuming it is because of the recent 1.1.0 update, assuming I'm not the only one getting errors now. It gets to different parts of the progress before it fails though when I rerun it, which I find odd. 

I actually run this automatically every day on my Linux server through WINE. It seems to work fine through WINE and I hope it continues to. Thanks for your work on this software - it's really useful.

For this report, though, I downloaded and ran on a Windows 10 machine as well. I ran x32 and x64 and all have failed. Sometimes it fails even before the first 'Processing records...' message. I tried verbose output but it didn't seem to give anything more specific on the failure.

Thanks.

> mcpe_viz v0.0.31 by Plethora777
> Reading XML from C:\Users\rawdr\Downloads\mcpe_viz-master\mcpe_viz.win64/mcpe_viz.xml
> Reading config from C:\Users\rawdr\Downloads\mcpe_viz-master\mcpe_viz.win64/mcpe_viz.cfg
> parseLevelFile: name=C:/Users/rawdr/Downloads/DRRv2/level.dat version=5 len=945
>   Found World Spawn: x=4 y=32767 z=4
>   Level name is [DRRv2]
> DB Open: dir=C:/Users/rawdr/Downloads/DRRv2
> DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
> Scan keys to get world boundaries
>   Bounds (chunk): DimId=0 X=(-140 141) Z=(-220 114)
>   Bounds (pixel): DimId=0 X=(-2240 2256) Z=(-3520 1824) Image=(4512 5360)
>   Bounds (chunk): DimId=1 X=(-54 42) Z=(-36 59)
>   Bounds (pixel): DimId=1 X=(-864 672) Z=(-576 944) Image=(1552 1536)
>   Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
>   Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
>   280265 records
> Active 'hide-top', 'force-top', and 'geojson-block':
>   'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
>   'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
>   'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
>   'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
>   'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
> Parse all leveldb records
> WARNING: getBlockName failed to find id=223 blockdata=0
> WARNING: getBlockName failed to find id=229 blockdata=0
> WARNING: getBlockName failed to find id=231 blockdata=0
> WARNING: getBlockName failed to find id=225 blockdata=0
> WARNING: getBlockName failed to find id=234 blockdata=0
> WARNING: getBlockName failed to find id=226 blockdata=0
> WARNING: getBlockName failed to find id=223 blockdata=0
> WARNING: getBlockName failed to find id=229 blockdata=0
> WARNING: getBlockName failed to find id=231 blockdata=0
> WARNING: getBlockName failed to find id=225 blockdata=0
> WARNING: getBlockName failed to find id=234 blockdata=0
> WARNING: getBlockName failed to find id=226 blockdata=0
>   Processing records: 10000 / 280265 (3.6%)
>   Processing records: 20000 / 280265 (7.1%)
>   Processing records: 30000 / 280265 (10.7%)
>   Processing records: 40000 / 280265 (14.3%)
>   Processing records: 50000 / 280265 (17.8%)
>   Processing records: 60000 / 280265 (21.4%)
>   Processing records: 70000 / 280265 (25.0%)
>   Processing records: 80000 / 280265 (28.5%)
>   Processing records: 90000 / 280265 (32.1%)
>   Processing records: 100000 / 280265 (35.7%)
>   Processing records: 110000 / 280265 (39.2%)
>   Processing records: 120000 / 280265 (42.8%)
>   Processing records: 130000 / 280265 (46.4%)
> WARNING: getBlockName failed to find id=236 blockdata=2
> WARNING: getBlockName failed to find id=236 blockdata=2
>   Processing records: 140000 / 280265 (50.0%)
> Player Position: Dimension=0 Pos=(12.5, 82.62, 34.5 @ image 2252, 3554) Rotation=(336.640625, 0.000000)
>   Processing records: 150000 / 280265 (53.5%)
>   Processing records: 160000 / 280265 (57.1%)
>   Processing records: 170000 / 280265 (60.7%)

**Comment by bsavage81** [comment]
I am having this same issue

**Comment by Plethora777** [comment]
Could you send a long a dropbox (or other) link to your world file so I can have a look at what's going on? Thanks!

**Comment by bsavage81** [comment]
https://drive.google.com/open?id=0B43virBKP-AQQWo1ZzZmMlNZekk

Here ya go, I hope this helps

**Comment by Plethora777** [comment]
Perfect - thanks!

**Comment by Plethora777** [comment]
Just pushed an update - give it a try.

**Comment by rawdr** [comment]
It's working now for me. Still seeing some of the 'getBlockName' warnings (but perhaps those were always there?). Also no 'Llama' in passive mob list yet.

But no more crash. Thank you!

> Parse all leveldb records
> WARNING: getBlockName failed to find id=223 blockdata=0
> WARNING: getBlockName failed to find id=229 blockdata=0
> WARNING: getBlockName failed to find id=231 blockdata=0
> WARNING: getBlockName failed to find id=225 blockdata=0
> WARNING: getBlockName failed to find id=234 blockdata=0
> WARNING: getBlockName failed to find id=226 blockdata=0
> WARNING: getBlockName failed to find id=223 blockdata=0
> WARNING: getBlockName failed to find id=229 blockdata=0
> WARNING: getBlockName failed to find id=231 blockdata=0
> WARNING: getBlockName failed to find id=225 blockdata=0
> WARNING: getBlockName failed to find id=234 blockdata=0
> WARNING: getBlockName failed to find id=226 blockdata=0
>   Processing records: 10000 / 306236 (3.3%)
>   Processing records: 20000 / 306236 (6.5%)
>   Processing records: 30000 / 306236 (9.8%)
>   Processing records: 40000 / 306236 (13.1%)
>   Processing records: 50000 / 306236 (16.3%)
>   Processing records: 60000 / 306236 (19.6%)
>   Processing records: 70000 / 306236 (22.9%)
>   Processing records: 80000 / 306236 (26.1%)
>   Processing records: 90000 / 306236 (29.4%)
>   Processing records: 100000 / 306236 (32.7%)
>   Processing records: 110000 / 306236 (35.9%)
>   Processing records: 120000 / 306236 (39.2%)
>   Processing records: 130000 / 306236 (42.5%)
> WARNING: getBlockName failed to find id=236 blockdata=2
> WARNING: getBlockName failed to find id=236 blockdata=2
>   Processing records: 140000 / 306236 (45.7%)
> Player Position: Dimension=0 Pos=(12.5, 82.62, 34.5 @ image 2252, 3554) Rotation=(3.691406, -90.000000)
>   Processing records: 150000 / 306236 (49.0%)
>   Processing records: 160000 / 306236 (52.2%)
>

**Comment by bsavage81** [comment]
Still giving a runtime error when it gets to image creation on an all images scan with the file I sent you.

**Comment by Plethora777** [comment]
@bsavage81 I'm looking at that right now and it looks like a separate issue -- the world is too large for the current code to handle.  Open another ticket for that.  I'm going to close this one.
