### ISSUE TITLE
Non-ASCII sign text not displayed correctly in the web app

### ISSUE THREAD

**Issue by SpecLad** [Plethora777/mcpe_viz#37]
For example, "Осторожно" is displayed as "РћСЃС‚РѕСЂРѕР¶РЅРѕ".

The geojson file actually has the text right, it's just not interpreted by the browser correctly, because it's encoded in UTF-8. An easy fix would be to add `charset="utf-8"` to the `script` element that loads the geojson file, or `<meta charset="utf-8" />` inside the `head`.

**Comment by Plethora777** [comment]
Thanks for the tip.  I added the <meta> approach in the update today.  I'll close this issue for now.  If there is still an issue, please feel free to open another.
