### ISSUE TITLE
layers cant be loaded if content is served on a server(XAMPP)

### ISSUE THREAD

**Issue by Thunder33345** [Plethora777/mcpe_viz#4]
so i came across this problem where layers wont be loaded if it is served through a XAMPP it will say "that image is not available...."

i dont know this is the server fault or mcpe viz itself but please investigate
detail:
XAMPP v3.2.1
localhost

thanks

**Comment by Plethora777** [comment]
Need a lot more details to figure out what is going on here.  

Can you post:

* The exact error message you see in the browser

* Any error messages in the XAMPP log?

* What settings you used when you ran mcpe_viz -- e.g. did you select "Most images" and find that numbered layers were not working?  If so, you need to select "All images".

**Comment by Thunder33345** [comment]
well for some reason it now works after i re start XAMPP
offtopic for some reason the script dont like to load when run offline

**Comment by Plethora777** [comment]
Well that's good news :) I'll close this issue.

Re scripts not running offline - probably because it loads some js libraries from the net.

**Comment by Thunder33345** [comment]
i will try to see if that is possible to re produce that
maybe it is XAMPP apache crashed after over loaded by my 6Xmb world therefore the script wont find the layers files since apache inst serving
