### ISSUE TITLE
1.2 beta fails

### ISSUE THREAD

**Issue by richhuff** [Plethora777/mcpe_viz#41]
The new Minecraft 1.2 beta 1 and 2 cause mcpe_vis to fail with message:

Error
MCPE Vis failed.  See Progress window for details.  If you consistently have this problem, you should switch from mcpe_vis win32 to win64, or vice versa.

The world zip file is too big to attach here.  (32 MB)  The log zip file is attached.

[BetaWorldLog.zip](https://github.com/Plethora777/mcpe_viz/files/1202568/BetaWorldLog.zip)

**Comment by Plethora777** [comment]
Thanks.  Please have a look at the update I just pushed to see if it resolves this issue, and let me know.

**Comment by richhuff** [comment]
On Tue, 2017-08-15 at 15:27 +0000, Plethora777 wrote:
> Thanks.  Please have a look at the update I just pushed to see if it
> resolves this issue, and let me know.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thanks!  It no longer fails.  The generated map looks good as far as I
can tell.Keep up the good work!
Rich
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/Plethora7
> 77/mcpe_viz","title":"Plethora777/mcpe_viz","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/Plethora777/mcpe_viz"}},"updates":{
> "snippets":[{"icon":"PERSON","message":"@Plethora777 in #41:
> Thanks.  Please have a look at the update I just pushed to see if it
> resolves this issue, and let me know."}],"action":{"name":"View
> Issue","url":"https://github.com/Plethora777/mcpe_viz/issues/41#issue
> comment-322501260"}}}

**Comment by Plethora777** [comment]
Excellent!  I'll close this.  Always feel free to open another if there are issues.
