### ISSUE TITLE
Crash in 1.2 Worlds

### ISSUE THREAD

**Issue by Shkyrockett** [Plethora777/mcpe_viz#42]
A few worlds modified by the MCPE Win 10 1.2.7.0 beta are causing mcpe_viz to crash after starting the leveldb parse.
Here is my smallest repro:
[§3Skyblock §2Challenge.mcworld.zip](https://github.com/Plethora777/mcpe_viz/files/1202837/3Skyblock.2Challenge.mcworld.zip)

**Comment by Plethora777** [comment]
Thanks.  Please have a look at the update I just pushed to see if it resolves this issue, and let me know.

**Comment by Shkyrockett** [comment]
Works perfectly. Thanks!
