### ISSUE TITLE
Help mcpe_vis killed my world! (resetted)

### ISSUE THREAD

**Issue by mysticdraco** [Plethora777/mcpe_viz#47]
Hello,

I have run this program and it was success, but after this i opend my world ingame, and it was resetted.
The folder was still the same size (of my world) but it was resetted so all i made was gone.

When i look at the world map, that mcpe_vis created it looks like what i build.

Is there a way to get it back in to level.dat? or what should i change to fix this?

**Comment by Thunder33345** [comment]
you are suppose to use it on a backup of your world
