### ISSUE TITLE
Cant compile mcpe_viz (CentOS 7.*)

### ISSUE THREAD

**Issue by mysticdraco** [Plethora777/mcpe_viz#48]
Hi, everything was fine untill i got to compile'ing mcpe_viz

make
if test ! -s build/Makefile; then  mkdir -p build ; cd build ; cmake .. ; fi
/bin/sh: cmake: command not found
make: *** [cmakebuild] Error 127

**Comment by mysticdraco** [comment]
After wressling with it, i found out that because of CentOS doesnt have cmake 3 yet, i installed it epel.
Changed in the make cmake to cmake3 that did fix some of it.

Now still its not getting trough yet.

 make
if test ! -s build/Makefile; then  mkdir -p build ; cd build ; cmake3 .. ; fi
Build: REGULAR
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake3/Modules/FindPNG.cmake:157 (find_package_handle_standard_args)
  CMakeLists.txt:84 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/draco/mcpe_viz/CMakeFiles/CMakeOutput.log".
make: *** [cmakebuild] Error 1


Will get trough and keep posting updates.. 
Will posibly help people having same problems.
(and maybe helpfull for a correct fix of make)

**Comment by Plethora777** [comment]
You probably need the libpng-devel RPM.  

FYI I compile on Fedora.  You might try a VM with fedora.

**Comment by Plethora777** [comment]
Closing an old issue -- please feel free to re-open or open a new issue if it's still a problem.
