### ISSUE TITLE
Block Light map no longer rendering. 

### ISSUE THREAD

**Issue by creuzerm** [Plethora777/mcpe_viz#49]
Areas visited in Better Together 1.2.3 will no longer render a Block Light map. Areas not visited yet in Better Together still correctly render the block light.

I turned on Verbose, and get a great many instances of the following error messages.  --verbose

ERROR: getBlockSkyLight_LevelDB_v3 get data out of bounds! (7239 >= 6145) (8 8 12)
ERROR: getBlockBlockLight_LevelDB_v3 get data out of bounds! (9287 >= 6145) (8 8 12)
ERROR: getBlockSkyLight_LevelDB_v3 get data out of bounds! (7247 >= 6145) (8 9 12)
ERROR: getBlockBlockLight_LevelDB_v3 get data out of bounds! (9295 >= 6145) (8 9 12)
ERROR: getBlockSkyLight_LevelDB_v3 get data out of bounds! (7255 >= 6145) (8 10 12)
ERROR: getBlockBlockLight_LevelDB_v3 get data out of bounds! (9303 >= 6145) (8 10 12)
ERROR: getBlockSkyLight_LevelDB_v3 get data out of bounds! (7263 >= 6145) (8 11 12)
ERROR: getBlockBlockLight_LevelDB_v3 get data out of bounds! (9311 >= 6145) (8 11 12)
ERROR: getBlockSkyLight_LevelDB_v3 get data out of bounds! (7271 >= 6145) (8 12 12)
ERROR: getBlockBlockLight_LevelDB_v3 get data out of bounds! (9319 >= 6145) (8 12 12)

I am guessing there is a change in 1.2 data formatting that hasn't been accounted for yet?

**Comment by Plethora777** [comment]
Sadly, as far as I can tell, the block light info is no longer stored in the world file so this feature will probably go away...
