### ISSUE TITLE
Issues with Converted world

### ISSUE THREAD

**Issue by picotazo** [Plethora777/mcpe_viz#51]
I have a Converted world from the Xbox one Edition of minecraft that I have been waiting to use with the bedrock version. 

As of Bedrock Version 1.2.5 I was finally able to convert it with a much better result, but once I have extracted the level.dat and associated DB files upon running the mcpe_viz_helper.exe I get the following error about 80 times right around 39% of the processing records portion but then continues.

Extra info the converted world plays mostly fine since the last patch no more missing chunks. I was also able to upload it to my realm and then download it to my Iphone. and transfer it to my PC for mcpe_viz to use.

"WARNING: UNKNOWN -- Found new chunkDimId=0x32373639 -- we are not prepared for that -- skipping chunk"

 I am able to view the overworld from within the webapp and the nether aswell, though the nether looks odd, as if a single nether quartz mineral node was duplicated all over the map. Both the overworld and the nether look stuck at a 2560x2560 map, and the End map is non-existent.  

And running mcpe_viz.exe from the command line I get the below error and it seems the program gets stuck in a loop.

"overworld-chunk: 104 -8 (type=0x2f) (size=6145) (image 4224 2432)
WARNING: UNKNOWN Byte 0 of 0x2f chunk: b0=[5 0x05]"

I'm going to poke around the Level.dat file and see if there are any references to data of the errors. And try and download the world from my PC and see if there is a difference with the data.

Any other assistance would be awesome and greatly appreciated 

Thanks again for this program,
Picotazo

**Comment by Plethora777** [comment]
Interesting & weird.  If you want to, you could zip up your world files and send me a link to grab them so I can have a look.

**Comment by picotazo** [comment]
Rockin I will do that..

Picotazo

Sent from my iPhone

On Nov 29, 2017, at 6:28 AM, Plethora777 <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting & weird. If you want to, you could zip up your world files and send me a link to grab them so I can have a look.

**Comment by picotazo** [comment]
Try this Link out let me know if it works.

https://1drv.ms/u/s!AhuGSi0hx-XdtGAhMQnQgkCZgxg6

Picotazo

**Comment by Plethora777** [comment]
Thanks for that.  I poked at it a bit.  The nether is strange for sure.  I just pushed a new version.  Give it a try.

**Comment by picotazo** [comment]
Pulled the new version.  its doing the tiles now but got the same error here is parts of the cmd line output  I cut out a bunch so as not to make a wall of text.

WARNING: UNKNOWN -- Found new chunkDimId=0x33373639 -- we are not prepared for that -- skipping chunk

  Processing records: 470000 / 1161221 (40.5%)
  Processing records: 480000 / 1161221 (41.3%)
  Processing records: 490000 / 1161221 (42.2%)
  Processing records: 500000 / 1161221 (43.1%)
  Processing records: 510000 / 1161221 (43.9%)
  Processing records: 520000 / 1161221 (44.8%)
  Processing records: 530000 / 1161221 (45.6%)
  Processing records: 540000 / 1161221 (46.5%)
WARNING: getItemName failed to find id=-1 extradata=-1

  Processing records: 550000 / 1161221 (47.4%)
  Processing records: 560000 / 1161221 (48.2%)
Player Position: Dimension=0 Pos=(326.088, 65.62, 249.711 @ image 3126, 4489) Rotation=(147.432068, 17.973877)
  Processing records: 570000 / 1161221 (49.1%)

  Processing records: 660000 / 1161221 (56.8%)
WARNING: getBlockName failed to find variant id=144 blockdata=0
WARNING: getBlockName failed to find id=144 blockdata=0

  Processing records: 730000 / 1161221 (62.9%)

WARNING: Did not find block variant for block(Wooden Double Slab) with blockdata=13 (0xd) MSG1

thanks again for everything..  this program rocks let me know if there is anything I can do to helpout.

Picotazo

**Comment by picotazo** [comment]
I spoke too soon...   ther 0.0.35 ver locks up @ this point.

Do Output: nether
  Generate Image
  Generate full-size slices
    Writing all images in one pass

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
