### ISSUE TITLE
Unable to find/read signs and wondering if we will be able to see contents of shulker boxes

### ISSUE THREAD

**Issue by spikebeer** [Plethora777/mcpe_viz#52]
I've tired in both Chrome and Firefox however find signs is not working, blank or not.
Also wondering if we will be able to see the contents of shulkers?
Thanks for the great program, it has been very useful keeping our realm honest.

**Comment by Plethora777** [comment]
The recent update should have solved the Shulker box thing - you should be able to see contents.  The sign thing indicates to me that your geojson file is not loading correctly.  

You could look at the web console (press F12 and reload the page) or send me a link to download your zip file to have a look.  Let me know :)

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
