### ISSUE TITLE
MCPE v1.4.0 large world fails to process in v0.0.37

### ISSUE THREAD

**Issue by Grimtoc** [Plethora777/mcpe_viz#58]
Plethora777,

Grimtoc here, just wanted to provide you with my world and the progress dump from the issue we spoke about on reddit.  The helper/command line works for newly created world (probably not large enough to cause issues though), but not on this world.  It's ~4 years old, so it's fairly large, which I'm now sure is the issue with the latest MC update.

Thanks again for taking a look!!

OneDrive Share containing world:
https://1drv.ms/f/s!Am-o89-AMM7TjcYMaOGwGLz0LrPsXA

Progress Dump:
mcpe_viz v0.0.37 by Plethora777
Reading XML from C:\Users\jbland\Desktop\MCPE VIZ 64/mcpe_viz.xml
Reading config from C:\Users\jbland\Desktop\MCPE VIZ 64/mcpe_viz.cfg
parseLevelFile: name=C:/Users/jbland/OneDrive/Minecraft Share/MPECANrTBAA=/level.dat version=8 len=1853
  Found World Spawn: x=16 y=32767 z=4
  Level name is [Anavrin - Copy]
DB Open: dir=C:/Users/jbland/OneDrive/Minecraft Share/MPECANrTBAA=
DB Open Status: OK (block_size=4096 bloom_filter_bits=10)
Scan keys to get world boundaries
  Bounds (chunk): DimId=0 X=(-317 374) Z=(-286 315)
  Bounds (pixel): DimId=0 X=(-5072 5984) Z=(-4576 5040) Image=(11072 9632)
  Bounds (chunk): DimId=1 X=(-26 38) Z=(-34 27)
  Bounds (pixel): DimId=1 X=(-416 608) Z=(-544 432) Image=(1040 992)
  Bounds (chunk): DimId=2 X=(0 0) Z=(0 0)
  Bounds (pixel): DimId=2 X=(0 0) Z=(0 0) Image=(16 16)
  1593137 records
Active 'hide-top', 'force-top', and 'geojson-block':
  'geojson' block: overworld - End Portal Frame (dimId=0 blockId=120 (0x78))
  'hide-top' block: nether - Bedrock (dimId=1 blockId=7 (0x07))
  'hide-top' block: nether - Netherrack (dimId=1 blockId=87 (0x57))
  'hide-top' block: nether - Lava (dimId=1 blockId=10 (0x0a))
  'hide-top' block: nether - Stationary Lava (dimId=1 blockId=11 (0x0b))
Parse all leveldb records
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 82) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 114) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 136) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 26) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
  Processing records: 10000 / 1593137 (0.6%)
NBT exception: (Invalid tag type: 130) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 54) (eof=false) (is=false)
NBT exception: (Invalid tag type: 98) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 12) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 119) (eof=false) (is=false)
NBT exception: (Invalid tag type: 112) (eof=false) (is=false)
NBT exception: (Invalid tag type: 112) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 45) (eof=false) (is=false)
NBT exception: (Invalid tag type: 64) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 14) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 51) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 57) (eof=false) (is=false)
NBT exception: (Invalid tag type: 12) (eof=false) (is=false)
NBT exception: (Invalid tag type: 48) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 26) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 28) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 24) (eof=false) (is=false)
NBT exception: (Invalid tag type: 102) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 170) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
  Processing records: 20000 / 1593137 (1.3%)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 136) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 224) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 221) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 119) (eof=false) (is=false)
NBT exception: (Invalid tag type: 80) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 148) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 187) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 102) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 34) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 33) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 20) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
  Processing records: 30000 / 1593137 (1.9%)

**Comment by Plethora777** [comment]
Just pushed an update which should fix this.  It's a bit hacky though as it does not address the new separate storage for water overlay.  Gotta think about that for a bit.  Let me know how things go for you.

**Comment by Grimtoc** [comment]
That got me working!  Took a while, and looks like some items were not read (old, not new stuff), but we are up and going and it didn't fail.  Lots of still undiscovered chucks that I know were actually uncovered, but that can wait until future updates!
![mc](https://user-images.githubusercontent.com/39565080/40444214-b931ccd2-5e96-11e8-8c3c-e3667a01d3bd.JPG)
Thanks again!

**Comment by zetoken** [comment]
Hmmm, I've been told that if you don't stay enough time (5 minutes) in a chunk and don't alter it then it isn't saved.
I've always have some undiscovered chunks in my world even if I saw them before.
I will try the update on my realm and compare with the old map previously made in 1.2.

**Comment by Plethora777** [comment]
Probably the water layer thing.  I'll keep working on that bit, but for now at least you can (mostly) see your world again :)

**Comment by amatulic** [comment]
Zetoken wrote: "I've been told that if you don't stay enough time (5 minutes) in a chunk and don't alter it then it isn't saved."

I'm skeptical of that. One of my standard uses of Minecraft creative mode is to fly around my world rapidly back and forth to create a map to view in mcpe_viz (my current favorite seed, BTW, is -1000 -- spawn point is near a village with a ravine cutting through it, with other villages and 3 end portals a reasonable distance away). I know for sure I am not spending more than a few seconds in each chunk and I am not modifying anything, yet the chunks get saved, and mcpe_viz shows them. Am I missing something?

I did notice one difference in my recent maps: chunk data used to be saved in a roughly circular shape around my character's location. Now it's saved in a roughly diamond shape with rounded corners and cleaner-looking edges without a sparse cloud of lone chunks beyond the radius boundary. That makes me think that Minecraft is saving data differently than before.

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
