### ISSUE TITLE
Errors with version 0.0.38

### ISSUE THREAD

**Issue by picotazo** [Plethora777/mcpe_viz#59]
Plethora,

I sent you a message via Reddit not sure if it went through but basically just me expressing my willingness to help.  here are some of the Errors I am getting with this version.

I am using Powershell to run the program, this is the command line I am using to run it very simple nothing fancy.

./mcpe_viz --db C:/Users/jmcavoy/Desktop/minecraftWorlds/Realm/ --out C:/Users/jmcavoy/Desktop/minecraftWorlds/Output --html-all

Here is a list of the most prevalent errors I am seeing while the program runs.

WARNING: getItemName failed to find id=455 extradata=0 **This one I know is the Trident**

If I can stop these from showing up I will have better luck finding more I just need to know/figureout the correct syntax.

**WARNING: getBlockByUname failed to find uname=minecraft:kelp
WARNING: getBlockByUname failed to find uname=minecraft:seagrass
WARNING: getBlockByUname failed to find uname=minecraft:grass**

More Errors:

WARNING: getBlockByUname failed to find uname=minecraft:concretePowder
WARNING: getBlockByUname failed to find uname=minecraft:seaLantern
WARNING: getBlockByUname failed to find uname=minecraft:stripped_jungle_log
WARNING: getItemName failed to find variant id=383 extradata=120
WARNING: getItemName failed to find id=383 extradata=120
WARNING: getBlockName failed to find variant id=144 blockdata=0
WARNING: getBlockName failed to find id=144 blockdata=0

NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 18) (eof=false) (is=false)
NBT exception: (Invalid tag type: 81) (eof=false) (is=false)
NBT exception: (Invalid tag type: 80) (eof=false) (is=false)
NBT exception: (Invalid tag type: 85) (eof=false) (is=false)
NBT exception: (Invalid tag type: 51) (eof=false) (is=false)
NBT exception: (Invalid tag type: 12) (eof=false) (is=false)
NBT exception: (Invalid tag type: 17) (eof=false) (is=false)
NBT exception: (Invalid tag type: 16) (eof=false) (is=false)
NBT exception: (Invalid tag type: 87) (eof=false) (is=false)
NBT exception: (Invalid tag type: 162) (eof=false) (is=false)
NBT exception: (Invalid tag type: 106) (eof=false) (is=false)
NBT exception: (Invalid tag type: 24) (eof=false) (is=false)

ERROR: Unknown biome 42 0x2d
ERROR: Unknown biome 43 0x2d
ERROR: Unknown biome 44 0x2d
ERROR: Unknown biome 45 0x2d

**After all that the program crashes here and throws me back to the prompt**

WARNING: getBlockByUname failed to find uname=minecraft:seagrass
WARNING: getBlockByUname failed to find uname=minecraft:seagrass
WARNING: getBlockByUname failed to find uname=minecraft:seagrass
WARNING: getBlockByUname failed to find uname=minecraft:seagrass
WARNING: getBlockByUname failed to find uname=minecraft:grass
Do Output: nether
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
PS C:\Users\jmcavoy\Downloads\mcpe_viz-master\mcpe_viz>

Thanks again for the program, please let me know how I can help

**Comment by amatulic** [comment]
Thanks, I was just about to report similar messages I'm getting with MCPE 1.4. They seem to be related to the new undersea features.

In addition to what was reported, I'm also getting

ERROR: Unknown biome 46 0x2e
ERROR: Unknown biome 47 0x2f

**Comment by darwinkim** [comment]
Huh. 0.0.38 is doing something weird for me with "web app filled with all images." It made a 40 GB log file until I stopped it. Filled mostly with this:

NBT exception: (Invalid tag type: 0) (eof=false) (is=false)

The log file was the only file generated. Maybe it has to do with my world size (126 MB). Generating log entries for every water block, perhaps?

**Comment by amatulic** [comment]
When I get these errors, I'm not running it on a data file that was generated in experimental mode, so there shouldn't be any experimental content. All the new undersea features (like seagrass) aren't experimental anymore in 1.4. I believe that experimental features would be things like turtles, turtle eggs, scutes, and turtle shells, which are to be released in 1.5 according to the Minecraft Wiki.

**Comment by Plethora777** [comment]
Yep the new chunk storage stuff is a bit strange and needs work in mcpe_viz.  Basically, the game now stores two sets of data for each cubic chunk -- regular and water (I believe).  It's a significant change and I'm still working out how to handle it properly.

Re messages like "ERROR: unknown biome" etc that just means that great new stuff is in the game, but is not in the XML files yet.  It should not cause an issue (other than that stuff will not be in the generated images).  I'll get to this, but you can work around it as mentioned above.  

One thing -- the new aquatic stuff doesn't have an ID so that makes it a bit tough to work with the existing approach in the XML files... I need to ponder this a little bit to figure out the right way forward.

Re messages like "NBT exception: (Invalid tag type: 0) (eof=false) (is=false)" -- those are big old bugs! :)  That means that the existing mcpe_viz code did not properly process cubic chunk data.  So you'll likely see corrupted chunks in your output image.  (This is related to the two sets of data for each chunk)

More soon!

**Comment by picotazo** [comment]
Thank you for the update Plethora let me know if there is any way I can help.

Peck

**Comment by MECU** [comment]
`<block id="0xED" name="Concrete Powder" uname="minecraft:concretepowder">` is now 
`<block id="0xED" name="Concrete Powder" uname="minecraft:concretePowder">`
(capital P in Powder)

I got color values use images off the Wiki and https://matkl.github.io/average-color/

I added in these values, but still get error messages that it cannot find the value:

```xml
<block id="0x104" name="Stripped Spruce Log" uname="minecraft:stripped_spruce_log" color="0x696c2d" opaque="0" spawnable="0" />
<block id="0x105" name="Stripped Birch Log" uname="minecraft:stripped_birch_log" color="0x696d2d" opaque="0" spawnable="0" />
<block id="0x106" name="Stripped Jungle Log" uname="minecraft:stripped_jungle_log" color="0x696e2d" opaque="0" spawnable="0" />
<block id="0x107" name="Stripped Acacia Log" uname="minecraft:stripped_acacia_log" color="0x69712c" opaque="0" spawnable="0" />
<block id="0x108" name="Stripped Dark Oak Log" uname="minecraft:stripped_dark_oak_log" color="0x69732c" opaque="0" spawnable="0" />
<block id="0x109" name="Stripped Oak Log" uname="minecraft:stripped_oak_log" color="0x696b2d" opaque="0" spawnable="0" />

<block id="0x181" name="Sea Grass" uname="minecraft:seagrass" color="0x0f2502" opaque="0" spawnable="0" />
<block id="0x182" name="Coral" uname="minecraft:coral" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x183" name="Coral Block" uname="minecraft:coral_block" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x184" name="Coral Fan" uname="minecraft:coral_fan" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x185" name="Dead Coral Fan" uname="minecraft:coral_fan_dead" color="0x282624" opaque="0" spawnable="0" />
<block id="0x186" name="Coral Fan" uname="minecraft:coral_fan_hang" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x187" name="Coral Fan" uname="minecraft:coral_fan_hang2" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x188" name="Coral Fan" uname="minecraft:coral_fan_hang3" color="0x0e1c40" opaque="0" spawnable="0" />
<block id="0x189" name="Kelp" uname="minecraft:kelp" color="0x233410" opaque="0" spawnable="0" />
<block id="0x190" name="Acacia Trapdoor" uname="minecraft:acacia_trapdoor" color="0x69712c" opaque="0" spawnable="0" />
<block id="0x191" name="Birch Trapdoor" uname="minecraft:birch_trapdoor" color="0x696d2d" opaque="0" spawnable="0" />
<block id="0x192" name="Dark Oak Trapdoor" uname="minecraft:dark_oak_trapdoor" color="0x69732c" opaque="0" spawnable="0" />
<block id="0x193" name="Jungle Trapdoor" uname="minecraft:jungle_trapdoor" color="0x696e2d" opaque="0" spawnable="0" />
<block id="0x194" name="Spruce Trapdoor" uname="minecraft:spruce_trapdoor" color="0x696c2d" opaque="0" spawnable="0" />
<block id="0x195" name="Acacia Pressure Plate" uname="minecraft:acacia_pressure_plate" color="0x69712c" opaque="0" spawnable="0" />
<block id="0x196" name="Birch Pressure Plate" uname="minecraft:birch_pressure_plate" color="0x696d2d" opaque="0" spawnable="0" />
<block id="0x196" name="Dark Oak Pressure Plate" uname="minecraft:dark_oak_pressure_plate" color="0x69732c" opaque="0" spawnable="0" />
<block id="0x196" name="Jungle Pressure Plate" uname="minecraft:jungle_pressure_plate" color="0x696e2d" opaque="0" spawnable="0" />
<block id="0x196" name="Spruce Pressure Plate" uname="minecraft:spruce_pressure_plate" color="0x696c2d" opaque="0" spawnable="0" />

<block id="0x19B" name="Sea Pickle" uname="minecraft:sea_pickle" color="0x060602" opaque="0" spawnable="0" />
```

Is there something else I need to do other than just add these values to the XML?

**Comment by picotazo** [comment]
Ok I'm not sure what I have done here but right now I have bubble columns showing up on my maps by adding:
<block id="0xd6" name="Bubble Column" uname="minecraft:bubble_column" color="0x02cffd" liquid="1" solid="0" opaque="0" spawnable="0" />
and remarking out:


However now Packed Ice is being identified on my maps as Bubble columns and Kelp is being identified as Shulker boxes of varying colors.

I attached my mcpe_viz.xml file changed the extention to .txt

any help in debugging what I screwed up would be awesome.

[mcpe_viz.txt](https://github.com/Plethora777/mcpe_viz/files/2207345/mcpe_viz.txt)

**Comment by budcodem** [comment]
Hi, anyone else fond something? I got millions of errors first - then succes rendering an open webapp.
But Still somehow no items are displayed inside chests.

[Error 1](https://imgur.com/18gWhxS)
[Error 2](https://imgur.com/jusOjQV)
[Render Success](https://imgur.com/ZyKriLC)
[Chest Error](https://imgur.com/mosKPmv)

**Comment by amatulic** [comment]
In the latest version I have, items are displayed inside chests --- but
only for chests that I have actually opened in the past.

**Comment by MECU** [comment]
Worked better for me. I still got a bunch of this:

`NBT exception: (Invalid tag type: 0) (eof=false) (is=false)`

otherwise, the only other block it couldn't find were (just a small sample):

```

WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=13 (0xd) MSG3
WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=14 (0xe) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=13 (0xd) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=12 (0xc) MSG3
WARNING: Did not find block variant for block(Stairs, Jungle Wood) with blockdata=13 (0xd) MSG3
WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=12 (0xc) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=8 (0x8) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=12 (0xc) MSG3
WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=12 (0xc) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=9 (0x9) MSG3
WARNING: Did not find block variant for block(Stairs, Spruce Wood) with blockdata=14 (0xe) MSG3
WARNING: Did not find block variant for block(Stairs, Birch Wood) with blockdata=13 (0xd) MSG3
```

They were all wood stairs related.

But the world rendered better. There were places where the block was "pink" and it said *UNKNOWN BLOCK*, but it defiantly worked better.

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.

**Comment by darwinkim** [comment]
I don't know if I should put this on this thread, but I can't run it on my world because I get NBT tag type exceptions on the log file until I run out of space on my computer. (Seriously, gigabytes of error messages.)

**Comment by MECU** [comment]
I'm on the latest version (v0.45).
`
INFO: Unmapped remote player: 14e725b7-2053-3056-bc21-f37929c4964b
INFO: Unmapped remote player: 2d5ad3e7-e77b-3887-a3c0-0809c118f9b2
INFO: Unmapped remote player: 300855d0-7ec8-3ef1-ad10-8e0a1187a140
INFO: Unmapped remote player: 431a493b-34ee-3541-ab09-f4fe918df423
INFO: Unmapped remote player: 91e33231-7799-3083-8f5d-55404561e686
INFO: Unmapped remote player: 941872a9-c443-3e3a-89a2-58a7169ccf25
INFO: Unmapped remote player: b33ddf97-cd69-3c72-88e3-ea77bba01e46
INFO: Unmapped remote player: c159e5d9-1299-3724-a14a-da53f4da7dcb
INFO: Unmapped remote player: server_25545cb4-935a-425a-8c47-6238ff4fc263
INFO: Unmapped remote player: server_4a3b225c-1284-4ba7-8fff-87174f33ca00
INFO: Unmapped remote player: server_6eb550a1-fb41-441d-8085-7d93fc90003e
INFO: Unmapped remote player: server_76f5ed8c-866f-427c-a1a9-7de19fc7e6f4
INFO: Unmapped remote player: server_da3df8eb-0593-4723-8d2c-97e6c3bdb511
INFO: Unmapped remote player: server_dc1e36c3-8806-4567-ade9-a4e3679d803f

WARNING: Did not find block variant for block (id=201 (0xc9) 'Purpur') with blockdata=3 (0x3) MSG1

ERROR: Invalid blockid=-127 (cubicy=1) (2 11 20)
ERROR: Invalid blockid=-81 (cubicy=4) (6 3 68)
ERROR: Invalid blockid=-95 (cubicy=5) (1 15 82)
ERROR: Invalid blockid=-94 (cubicy=4) (2 8 78)
ERROR: Invalid blockid=-103 (cubicy=4) (3 14 70)
ERROR: Invalid blockid=-43 (cubicy=1) (2 5 20)
`
cubicy is 0-7

The three numbers at the end vary

**Comment by MECU** [comment]
I'm not getting any error messages now, just this warning:

```
WARNING: Did not find block variant for block (id=201 (0xc9) 'Purpur') with blockdata=3 (0x3) MSG1
```

Thanks for all your work!

**Comment by Plethora777** [comment]
Just pushed an update that should fix this

**Comment by MECU** [comment]
on 0.48 and got nearly the same message:

```
WARNING: Did not find block variant for block (id=201 (0xc9) 'Purpur') with blockdata=3 (0x3) MSG3
```

**Comment by Plethora777** [comment]
@MECU That message just means that the XML file is not up to date.  If mcpe_viz ran completed successfully, that's a good thing :)

**Comment by ghost** [comment]
I'm no longer getting infinite error messages on my world. Web app seems to work correctly. Thanks for the fix!
