### ISSUE TITLE
mcpe_viz_helper not found

### ISSUE THREAD

**Issue by skribe** [Plethora777/mcpe_viz#6]
> Compile mcpe_viz_helper
>From the top directory of mcpe_viz:
> cd gui
> qmake
>If all goes well, you will have "mcpe_viz_helper" in release/

Hi:

I tried this on linux mint 17.3 and nothing appeared to happen (it went straight to the command line).  There's no sign of a 'release' folder.  Maybe there are missing packages?

After some hiccups the main compile seems to have worked btw.  Just no gui.

Cheers.

**Comment by Plethora777** [comment]
Thanks for pointing that out!  

I neglected to add a line after qmake:

> make

:)  Let me know how it goes.

**Comment by skribe** [comment]
Thanks mate.  That worked although there is still no 'release' directory created and mcpe_viz_helper needs to be copied to the same directory as mcpe_viz or it just sits there going DERP! =)

Cheers.

**Comment by Plethora777** [comment]
Thanks again - I'll update the README.  I'm going to close this ticket.  Feel free to open another one if anything else comes up :)
