### ISSUE TITLE
Issues generating a map from a Bedrock Realm

### ISSUE THREAD

**Issue by cwawak** [Plethora777/mcpe_viz#60]
Steps to reproduce:
1. Download backup of a Minecraft Bedrock Realm on Windows 10
2. Rename backup from .mcworld to .zip
3. Extract .zip
4. Point mcpe_viz_helper (downloaded from latest git) to the level.dat file in the .zip
5. Attempt to create map - all images, web app, any of these options give the same behavior.

Expected behavior:
Creates map

Actual behavior:
Web app is created, but with a blank, black map, HUGE (10GB+) log files with logs of the following errors:
Parse all leveldb records
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
[... and so on for ~10 gigs of logs or so ...]
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
    Row 1600 of 1680
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
Do Output: nether
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 16
Do Output: the-end
  Generate Image
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 16
Do Output: html viewer
Copying icon images
Done.

MCPE Viz completed successfully!
You can launch the web app now.

![2018-07-06](https://user-images.githubusercontent.com/1583877/42393156-79567f04-8123-11e8-8b5b-a79c9a790369.png)

[realm.zip](https://github.com/Plethora777/mcpe_viz/files/2171481/realm.zip)

**Comment by picotazo** [comment]
I have never had any luck with the .mcworld files.  for my realm I just download the realm from its setting button and then copy the contents of the newly created world to an alternate dir and let mcpe_viz work on it from there.

**Comment by Romaq** [comment]
It would be a beautiful thing if mcpe_viz could read .mcworld files "raw" rather than unzipped, and so on. As it is, if *I* create the world, the map program would be happy. If I try to map one from Marketplace, I think Marketplace uses a key that thwarts mcpe_viz from working. I've not used this software lately as I've been playing Java snapshots. When we return to Bedrock I'll see how mcpe_viz is working.

**Comment by ynleborg** [comment]
Same for me, 
NBT exception: (Invalid tag type: 0) (eof=false) (is=false)
in tens of gigs of log

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
