### ISSUE TITLE
MCPE_viz 0.38 crashes

### ISSUE THREAD

**Issue by mattlazarowitz** [Plethora777/mcpe_viz#61]
Both mcpe_viz.win32 and mcpe_viz.win64 are crashing 
On one OS, I actually get the opportunity to grab some crash details. 
I get a popup that says "mcpe_viz.exe has stopped working"
There is a button that says "view problem details".
For the 64 bit version, here are the details:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mcpe_viz.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b059ed1
  Fault Module Name:	libstdc++-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	599c3590
  Exception Code:	c0000005
  Exception Offset:	00000000000ca5b8
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1033
  Additional Information 1:	4f20
  Additional Information 2:	4f209e0281c8c7105cc59553a2bc42f2
  Additional Information 3:	a9d2
  Additional Information 4:	a9d2c956681a7d912b9c9a778a1ecddd

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Here are the details for the 32 bit version:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mcpe_viz.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b059e4f
  Fault Module Name:	libstdc++-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	599c33cd
  Exception Code:	c0000005
  Exception Offset:	000d08ff
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement
is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

I've attached the log file from both runs.
[64_bit.log](https://github.com/Plethora777/mcpe_viz/files/2172433/64_bit.log)
[32_bit.log](https://github.com/Plethora777/mcpe_viz/files/2172436/32_bit.log)

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
