### ISSUE TITLE
With 0.16.x mobs can't be shown on the map

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#7]
With a map generated from an 0.16.x world I can't view mobs or even the player.  Selecting them in the passive or hostile mobs menus shows nothing - even if I'm certain the mobs are there.

Other things such as nether portals and spawners seem to show as before

**Comment by Plethora777** [comment]
Thanks for pointing that out!  I've got a fix.  I'll post it after a bit of testing.

**Comment by Plethora777** [comment]
Just posted an update - have a try :)

**Comment by phunni** [comment]
that seems to have fixed it!

**Comment by Plethora777** [comment]
Great!  Thanks
