### ISSUE TITLE
All output on error channel

### ISSUE THREAD

**Issue by MECU** [Plethora777/mcpe_viz#70]
I'm using this command:

```
./mcpe_viz --db /home/ --out /home/birch-lake --no-force-geojson --quiet --html-all
```

The `--quiet` flag seems to have no effect on the output being reduced.

* If I append `> temp.log` to the command, all the output remains and there is nothing in the log file.
* If I append `&> temp.log` to the command, all the output is suppressed and in the log file.

I would expect that `--quiet` would suppress the output details somewhat, and the output is on the correct channel for capturing purposes.

**Comment by Plethora777** [comment]
The --quiet flag mostly tries to make the .log file less huge.  The regular output needs to be the way that it is so that the GUI is reasonable... Hope that works for you :)
