### ISSUE TITLE
Turtles?

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#74]
Any chance of adding turtles to the passive mobs list? Is there a way I can tweak the xml/configs to add this myself?
None of the turtle farms I've tried in bedrock work properly, so being able to find the turtles easily would be useful.
On a happier note - the latest version (0.44) runs without any errors/warnings in the output for the first time in ages! :-)

**Comment by Plethora777** [comment]
Pushed an update with Turtles (and other stuff).  Give it a try, if all is good, close this.

**Comment by Plethora777** [comment]
Silly typo - fixed in new push.  If all is good, go ahead and close this.

**Comment by phunni** [comment]
There's still a typo in the word turtle: TUrtle

That said, it works perfectly, so I'm going to close it.
