### ISSUE TITLE
All Images and Web App with All Images Crashes

### ISSUE THREAD

**Issue by Valacarnage** [Plethora777/mcpe_viz#75]
Continuing to experiencing issue with All Image and Web app with All Images crashing.  Sames results on world that was tested on as well as the latest download of realm world.

NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=6692) (parseNbtQuiet)
    Row 3840 of 9728
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=3 (0x3) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
WARNING: Did not find block variant for block (id=182 (0xb6) 'Red Sandstone Slab') with blockdata=11 (0xb) MSG1
    Row 4160 of 9728
    Row 4480 of 9728

**Comment by Plethora777** [comment]
Try it again with the new update and let me know

**Comment by Plethora777** [comment]
Just pushed an update that should fix this

**Comment by Plethora777** [comment]
I believe the recent push solved this, so I'm going to close this. Feel free to re-open or open a new ticket as needed.
