### ISSUE TITLE
Errors in v 0.45 64bit

### ISSUE THREAD

**Issue by amatulic** [Plethora777/mcpe_viz#76]
Working fine on my small survival world, but getting thousands of these on my very large creative world:

```
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=778) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=76) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=1206) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=475) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=1297) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=329) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=771) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=154) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=1804) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=1205) (parseNbtQuiet)

```
All lines identical except for the buflen value. It's been 10 minutes and it's still going like this. I'll terminate it soon if it doesn't do anything different after a few more minutes.

**Comment by Plethora777** [comment]
Found and resolved that issue -- still chasing another before I push a new update, probably tonight

**Comment by Gaston-Fouche-Neuralify** [comment]
Have had a problem with detection of villages..


Sent via the Samsung Galaxy S8+, an AT&T 4G LTE smartphone
-------- Original message --------From: Plethora777 <notifications@github.com> Date: 12/29/18  7:56 AM  (GMT-06:00) To: Plethora777/mcpe_viz <mcpe_viz@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [Plethora777/mcpe_viz] Errors in v 0.45 64bit (#76) 
Found and resolved that issue -- still chasing another before I push a new update, probably tonight

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Plethora777/mcpe_viz","title":"Plethora777/mcpe_viz","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Plethora777/mcpe_viz"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Plethora777 in #76: Found and resolved that issue -- still chasing another before I push a new update, probably tonight"}],"action":{"name":"View Issue","url":"https://github.com/Plethora777/mcpe_viz/issues/76#issuecomment-450494913"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Plethora777/mcpe_viz/issues/76#issuecomment-450494913",
"url": "https://github.com/Plethora777/mcpe_viz/issues/76#issuecomment-450494913",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by amatulic** [comment]
Ah, It's still doing stuff. It finished that long list of errors like this:
...
Processing records: 400000 / 401733 (99.6%)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=199) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=80) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=156) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=117) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=199) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=154) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=192) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=273) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=154) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=76) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=192) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=537) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=199) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=154) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=117) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=230) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=199) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=76) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=152) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=199) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=197) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=76) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=75) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=194) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=195) (parseNbtQuiet)
NBT exception: (Invalid tag type: 0) (eof=false) (is=false) (buflen=233) (parseNbtQuiet)
Read 401733 records
Status: OK
Check Spawnable: Dimension 'overworld' (0)
Check Spawnable: Dimension 'nether' (1)
Check Spawnable: Dimension 'the-end' (2)
Do Output: overworld
  Generate Image
    Info: World (0, 0) is at image (2352, 6032)
    Info: World Spawn (124, 4) is at image (2476, 6036)
  Generate Biome Image
  Generate Grass Image
  Generate Height Column Image
  Generate Height Column (grayscale) Image
  Generate Height Column (alpha) Image
  Generate Block Light Image
  Generate Sky Light Image
  Generate Slime Chunks Image
  Generate Shaded Relief Image
  Generate full-size slices
    Writing all images in one pass
    Row 0 of 9600
ERROR: Invalid blockid=-81 (cubicy=4) (0 1 66)
ERROR: Invalid blockid=-81 (cubicy=4) (0 1 67)
ERROR: Invalid blockid=-81 (cubicy=4) (1 11 68)
ERROR: Invalid blockid=-81 (cubicy=4) (1 11 69)
...
and now it's generating a large list of invalid block IDs. Rather than dump it all here, these are the IDs listed as invalid:
-12
-40
-58
-81
-82
-92
-94
-95
-116
-117

(as far as I can tell, this is a millions lines long).

Finally it finished those invalid block messages interspersed with NBT error messages, and began doing the Nether, during which it generated the same 2 kinds of error messages, and finally built the .png files.

The seed for this world is -1000 if that matters. The database for this world was probably last updated with Minecraft 1.6 (and I'm now up to 1.8).

After the above, my next test was to load and save this world with Minecraft 1.8 and see if that made a difference.... but it didn't. I got the same results.

**Comment by amatulic** [comment]
Oops, didn't see the reply above. If fixed already, close this.

**Comment by Plethora777** [comment]
Just pushed an update that fixes the "NBT exception" issue and sort of punts on the "Invalid blockid" issue :)

**Comment by MECU** [comment]
I'm not getting any error messages now, just this warning:

```
WARNING: Did not find block variant for block (id=201 (0xc9) 'Purpur') with blockdata=3 (0x3) MSG1
```

**Comment by amatulic** [comment]
Thanks! I'm going to close this. I am not seeing any unusual error messages in 0.47. I'll open a new ticket if I see anything strange.
