### ISSUE TITLE
Some blocks turn green when choosing a specific layer

### ISSUE THREAD

**Issue by dzx-dzx** [Plethora777/mcpe_viz#77]
Before:
![screenshot from 2018-12-31 00-28-24](https://user-images.githubusercontent.com/31068367/50549190-89045880-0c93-11e9-86d4-f5d0f0aa70a8.png)
After:
![screenshot from 2018-12-31 00-29-08](https://user-images.githubusercontent.com/31068367/50549191-8c97df80-0c93-11e9-975a-9e6174a31b0b.png)

**Comment by Plethora777** [comment]
Just pushed an update that should fix this

**Comment by Plethora777** [comment]
I believe the recent update solved this, so I'm gonna close.  Feel free to open a new one if it happens again.
