### ISSUE TITLE
Protect against backslash in signs for out.geojson

### ISSUE THREAD

**Issue by edonaldson** [Plethora777/mcpe_viz#8]

**Comment by edonaldson** [comment]
Some signs contain the \ character.  JSON is misinterpreting it.  I think that it can be translated to \\

The same may also be true of the " character on a sign, but I have not confirmed.

**Comment by Plethora777** [comment]
I'll look into this.  An update for 0.17 is going to come soon too.  I'll roll this fix into that.

**Comment by Plethora777** [comment]
Just pushed an update which should resolve this.  Let me know!

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.
