### ISSUE TITLE
State of Repo

### ISSUE THREAD

**Issue by scp-r** [Plethora777/mcpe_viz#93]
Just curious how maintained this repo is, because there is no commit since 2019

I'm working on a new fork (<https://github.com/bedrock-viz/bedrock-viz.git> of this repository to fix bugs and add new features

completed:
- [x] patched leveldb from google/leveldb, which brings cmake support
- [x] new CMakeLists.txt, compiles on macOS and ubuntu 18.04

todo:
- [x] compile on Windows using MSVC, with cmake and vcpkg
- [ ] support new items in Minecraft Bedorck 1.12 and 1.13
- [x] a working new release
- [ ] all todos in source code
- [ ] split web app and cli tool

any help would be appreciated

**Comment by johnall203** [comment]
I use this tool a lot. I don't program but I can test. Would a tester
benefit your efforts?

**Comment by scp-r** [comment]
@johnall203 any help is welcome.
Currently there is no unit test in code, so a PR with unit test would be great. And I think to test the viz tool,  we gonna need a lot of world saves to make sure any block/item can be parsed correctly.

Gtest would be used in unit test, and the build instruction is <https://github.com/bedrock-viz/bedrock-viz/blob/master/docs/BUILD.md>

**Comment by counterfitninja** [comment]
Not a code/ tester, but I am an infrastructure guy with quite few different worlds dotted around. Happy to do enduser testing/ Beta testing if you want.

**Comment by mrucidlo** [comment]
Same here, I can help to beta test...

**Comment by scp-r** [comment]
a new version has been released: <https://github.com/bedrock-viz/bedrock-viz/releases/tag/v0.1.1>

**Comment by mrucidlo** [comment]
> a new version has been released: https://github.com/bedrock-viz/bedrock-viz/releases/tag/v0.1.1

Thank you! also working perfectly, I've noticed that options for Blocks are empty.

**Comment by juliankay** [comment]
I'm here to help the community where possible! I'll try this build tonight, thanks @jasper-wan

**Comment by amatulic** [comment]
I'm so happy to see this fork @jasper-wan -- MCPE Viz was working OK for me up through Bedrock 1.11 (missing a lot of the newer features but still generating a map sufficient for my needs) but doesn't work on 1.13, I just get blank maps with mob and item locations.

**Comment by Romaq** [comment]
Something I think would be useful is a "from scratch" version of https://www.planetminecraft.com/project/qmagnets-texture-pack-test-map-13w03a/ for the current Bedrock. This could be useful as a reference test for MCPE Viz as well as testing texture packs. If everyone is using the same map with all current blocks and tiles for reference, this would likely be a huge aid in debugging.

**Comment by amatulic** [comment]
> Something I think would be useful is a "from scratch" version of https://www.planetminecraft.com/project/qmagnets-texture-pack-test-map-13w03a/ for the current Bedrock.

Tha's for Java edition 1.12.1 (from 3 years ago), not Bedrock 1.12.1 (from last year). I doubt it would be compatible.

**Comment by Romaq** [comment]
It isn't compare, which is why it would be a big deal if someone did this fresh for Bedrock.

**Comment by WillemvdPijl** [comment]
Hey man, I am a developer and I've been using this tool for a while now. After every Minecraft update new problems start to pop up. I would be happy to help!
